apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
  namespace: jenkins-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: john1436gilbert/eks-app:latest
        ports:
        - containerPort: 5000

